cabal-version:      3.0

name:               project


version:            0.1.0.0

license:            NONE

author:             Siren B.

maintainer:         siren.bjoroy@uib.no

category:           Web
build-type:         Simple

extra-doc-files:    CHANGELOG.md

common warnings
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

executable project
    import:           warnings

    main-is:          Main.hs

    other-modules:      
        DB, 
        API,
        Server, 
        Pages,
        Static
        
    build-depends:    
        base ^>=4.18.3.0,
        selda,
        selda-sqlite,
        text,
        lucid,
        servant,
        servant-lucid,
        servant-server,
        warp,
        network-uri,
        bytestring,
        file-embed,
        stm,
        mtl,
        aeson,
        http-api-data
        
    -- Directories containing source files.
    hs-source-dirs:   app

    -- Base language which the package is written in.
    default-language: GHC2021
